---
- hosts: aws
  user: ec2-user
  become: yes
  vars_files:
    - ./vars/variables.yml
  vars_prompt:
  - name: "user_name"
    prompt: "backlogのIDを入力してください"
    private: no
  - name: "password"
    prompt: "backlogのパスワードを入力してください"
    private: yes
  roles:
    - common
    - node-exporter
    - php
    - mysql
    - composer
    - git clone
    - nginx